### ISSUE TITLE
任务1 京东首页顶部菜单的框架制作

### ISSUE THREAD

**Issue by Easy-MJ** [Easy-MJ/html-study#1]

**Comment by Easy-MJ** [comment]
> 问题1

**Comment by Easy-MJ** [comment]
> 问题2：开发网站的步骤
- 先设计大体布局
- 设计细分内容

**Comment by Easy-MJ** [comment]
> 问题3：固定高度的内容如何垂直对齐呢？
``` css
只需要给内容设置行高等于高度即可；
#shortcut-2014 {
    width: 100%;
    height: 30px;
    line-height: 30px;
    background: #F1F1F1;
}
```

**Comment by Easy-MJ** [comment]
> 问题4：如何去除网页中的元素默认内外边距呢？
``` css
a, address, b, big, blockquote, body, center, cite, code, dd, del, div, dl, dt, em, fieldset, font, form, h1, h2, h3, h4, h5, h6, html, i, iframe, img, ins, label, legend, li, ol, p, pre, small, span, strong, u, ul, var {
    margin: 0;
    padding: 0;
}
```

**Comment by Easy-MJ** [comment]
问题5：如何设置页面的字体样式及背景颜色呢？
``` css
body {
    font: 12px/150% Arial,Verdana,"\5b8b\4f53";
    color: #666;
    background: #fff;
}
```
