### ISSUE TITLE
任务11 京东商品分类菜单设计

### ISSUE THREAD

**Issue by Easy-MJ** [Easy-MJ/html-study#11]

**Comment by Easy-MJ** [comment]
分类菜单项页面结构
``` html
<div class="dd-inner">
    <div class="item">
        <h3><a target="_blank" href="#">家用电器</a></h3><i>&gt;</i>
    </div>
    <div class="item">
        <h3>
            <a target="_blank" href="#">手机</a>、
            <a target="_blank" href="#">运营商</a>、
            <a target="_blank" href="#">数码</a>
        </h3>
        <i>&gt;</i>
    </div>
    <div class="item">
        <h3><a target="_blank" href="#">电脑、办公</a></h3><i>&gt;</i>
    </div>
    <div class="item">
        <h3>
            <a target="_blank" href="#">家居</a>、
            <a target="_blank" href="#">家具</a>、
            <a target="_blank" href="#">厨具</a>、
            <a target="_blank" href="#">家装</a>
        </h3>
        <i>&gt;</i>
    </div>
    <div class="item">
        <h3>
            <a target="_blank" href="#">男装</a>、
            <a target="_blank" href="#">女装</a>、
            <a target="_blank" href="#">童装</a>、
            <a target="_blank" href="#">内衣</a>
        </h3>
        <i>&gt;</i>
    </div>
    <div class="item">
        <h3>
            <a target="_blank" href="#">个护化妆</a>、
            <a target="_blank" href="#">清洁用品</a>、
            <a target="_blank" href="#">宠物</a>
        </h3>
        <i>&gt;</i>
    </div>
    <div class="item">
        <h3>
            <a target="_blank" href="#">鞋靴</a>、
            <a target="_blank" href="#">箱包</a>、
            <a target="_blank" href="#">珠宝</a>、
            <a target="_blank" href="#">奢侈品</a>
        </h3>
        <i>&gt;</i>
    </div>
    <div class="item">
        <h3>
            <a target="_blank" href="#">运动户外</a>、
            <a target="_blank" href="#">钟表</a>
        </h3>
        <i>&gt;</i>
    </div>
    <div class="item">
        <h3>
            <a target="_blank" href="#">汽车</a>、
            <a target="_blank" href="#">汽车用品</a>
        </h3>
        <i>&gt;</i>
    </div>
    <div class="item">
        <h3>
            <a target="_blank" href="#">母婴</a>、
            <a target="_blank" href="#">玩具乐器</a>
        </h3>
        <i>&gt;</i>
    </div>
    <div class="item">
        <h3>
            <a target="_blank" href="#">食品</a>、
            <a target="_blank" href="#">酒类</a>、
            <a target="_blank" href="#">生鲜</a>、
            <a target="_blank" href="#">特产</a>
        </h3>
        <i>&gt;</i>
    </div>
    <div class="item">
        <h3><a target="_blank" href="#">医药保健</a></h3><i>&gt;</i>
    </div>
    <div class="item">
        <h3>
            <a target="_blank" href="#">图书</a>、
            <a target="_blank" href="#">音像</a>、
            <a target="_blank" href="#">电子书</a>
        </h3>
        <i>&gt;</i>
    </div>
    <div class="item">
        <h3>
            <a target="_blank" href="#">彩票</a>、
            <a target="_blank" href="#">旅行</a>、
            <a target="_blank" href="#">充值</a>、
            <a target="_blank" href="#">票务</a>
        </h3>
        <i>&gt;</i>
    </div>
    <div class="item">
        <h3>
            <a target="_blank" href="#">理财</a>、
            <a target="_blank" href="#">众筹</a>、
            <a target="_blank" href="#">白条</a>、
            <a target="_blank" href="#">保险</a>
        </h3>
        <i>&gt;</i>
    </div>
</div>
```

**Comment by Easy-MJ** [comment]
页面结构设计
``` html
<div id="nav-2014">
    <div class="w">
        <!--全部商品分类菜单-->
        <div id="categorys-2014" class="dorpdown">
            <div class="dt">
                <a target="_blank" href="#">全部商品分类</a>
            </div>
            <div class="dd">
            <div class="dd-inner">
                <div class="item">
                    <h3><a target="_blank" href="#">家用电器</a></h3><i>&gt;</i>
                </div>
                <div class="item">
                    <h3>
                        <a target="_blank" href="#">手机</a>、
                        <a target="_blank" href="#">运营商</a>、
                        <a target="_blank" href="#">数码</a>
                    </h3>
                    <i>&gt;</i>
                </div>
                <div class="item">
                    <h3><a target="_blank" href="#">电脑、办公</a></h3><i>&gt;</i>
                </div>
                <div class="item">
                    <h3>
                        <a target="_blank" href="#">家居</a>、
                        <a target="_blank" href="#">家具</a>、
                        <a target="_blank" href="#">厨具</a>、
                        <a target="_blank" href="#">家装</a>
                    </h3>
                    <i>&gt;</i>
                </div>
                <div class="item">
                    <h3>
                        <a target="_blank" href="#">男装</a>、
                        <a target="_blank" href="#">女装</a>、
                        <a target="_blank" href="#">童装</a>、
                        <a target="_blank" href="#">内衣</a>
                    </h3>
                    <i>&gt;</i>
                </div>
                <div class="item">
                    <h3>
                        <a target="_blank" href="#">个护化妆</a>、
                        <a target="_blank" href="#">清洁用品</a>、
                        <a target="_blank" href="#">宠物</a>
                    </h3>
                    <i>&gt;</i>
                </div>
                <div class="item">
                    <h3>
                        <a target="_blank" href="#">鞋靴</a>、
                        <a target="_blank" href="#">箱包</a>、
                        <a target="_blank" href="#">珠宝</a>、
                        <a target="_blank" href="#">奢侈品</a>
                    </h3>
                    <i>&gt;</i>
                </div>
                <div class="item">
                    <h3>
                        <a target="_blank" href="#">运动户外</a>、
                        <a target="_blank" href="#">钟表</a>
                    </h3>
                    <i>&gt;</i>
                </div>
                <div class="item">
                    <h3>
                        <a target="_blank" href="#">汽车</a>、
                        <a target="_blank" href="#">汽车用品</a>
                    </h3>
                    <i>&gt;</i>
                </div>
                <div class="item">
                    <h3>
                        <a target="_blank" href="#">母婴</a>、
                        <a target="_blank" href="#">玩具乐器</a>
                    </h3>
                    <i>&gt;</i>
                </div>
                <div class="item">
                    <h3>
                        <a target="_blank" href="#">食品</a>、
                        <a target="_blank" href="#">酒类</a>、
                        <a target="_blank" href="#">生鲜</a>、
                        <a target="_blank" href="#">特产</a>
                    </h3>
                    <i>&gt;</i>
                </div>
                <div class="item">
                    <h3><a target="_blank" href="#">医药保健</a></h3><i>&gt;</i>
                </div>
                <div class="item">
                    <h3>
                        <a target="_blank" href="#">图书</a>、
                        <a target="_blank" href="#">音像</a>、
                        <a target="_blank" href="#">电子书</a>
                    </h3>
                    <i>&gt;</i>
                </div>
                <div class="item">
                    <h3>
                        <a target="_blank" href="#">彩票</a>、
                        <a target="_blank" href="#">旅行</a>、
                        <a target="_blank" href="#">充值</a>、
                        <a target="_blank" href="#">票务</a>
                    </h3>
                    <i>&gt;</i>
                </div>
                <div class="item">
                    <h3>
                        <a target="_blank" href="#">理财</a>、
                        <a target="_blank" href="#">众筹</a>、
                        <a target="_blank" href="#">白条</a>、
                        <a target="_blank" href="#">保险</a>
                    </h3>
                    <i>&gt;</i>
                </div>
            </div>
            </div>
        </div>
    </div>
</div>
```

**Comment by Easy-MJ** [comment]
样式结构设计
``` css
#nav-2014 { /*宽度默认100%*/
    height: 44px;
    border-bottom: 2px solid #B1191A; /*底边线2px填充*/
    _overflow: hidden;
}

#nav-2014 .w {
    position: relative;
    z-index: 9;
    height: 44px;
}

#categorys-2014 {
    float: left;
    position: relative;
    z-index: 10;
    width: 210px;
    height: 44px;
    overflow: visible;/*下面的菜单可以看见，如果修改为hidden则看不到下面的分类菜单*/
    background: #B1191A;
}

#categorys-2014 .dt a {
    display: block;/*行级元素变为块元素，往往需要制定宽度和高度来使用*/
    width: 190px;
    height: 44px;
    padding: 0 10px;
    background: #B1191A;
    font: 400 15px/44px "microsoft yahei";
    color: #fff;
    text-decoration: none;/*去掉a标签的下划线样式*/
}

#categorys-2014 .dd {
    height: 466px;/*指定整个菜单高度466px*/
    background: #c81623;
    margin-top: 2px;
}

#categorys-2014 .dd-inner .item { /*菜单项样式*/
    border-left: 1px solid #b61d1d;
    position: relative;
    z-index: 1;
    height: 31px;
    color: #fff;
}

#categorys-2014 .dd-inner h3 {
    position: absolute;/*设置position为absolute，则一般都会存在top、left、right、bottom属性，否则基本可以不设置，除了可以被继承没有什么作用*/
    z-index: 2;
    height: 31px;
    padding: 0 10px;
    line-height: 31px;
    font-family: "microsoft yahei";
    font-size: 14px;
    font-weight: 400;
}

#categorys-2014 .dd-inner .item a {
    color: #fff;
}

#categorys-2014 .dd-inner i { /*箭头定位在菜单项右侧样式*/
    position: absolute;
    z-index: 1;
    top: 9px;
    right: 14px;
    width: 4px;
    height: 14px;
    font: 400 9px/14px consolas;
}
```
