### ISSUE TITLE
任务12 京东分类横向菜单设计

### ISSUE THREAD

**Issue by Easy-MJ** [Easy-MJ/html-study#12]

**Comment by Easy-MJ** [comment]
页面结构设计
``` html
<div id="navitems-2014">
    <ul id="navitems-group1">
        <li class="fore1">
            <a target="_blank" href="#">服装城</a>
        </li>
        <li class="fore1">
            <a target="_blank" href="#">美妆馆</a>
        </li>
        <li class="fore1">
            <a target="_blank" href="#">京东超市<i style="position: absolute;top:0;background: url(images/57cd2852N89da6ac5.jpeg) 0 0 no-repeat;width: 38px;height: 30px;"></i>
            </a>
        </li>
        <li class="fore1">
            <a target="_blank" href="#">生鲜</a>
        </li>
    </ul>
    <ul id="navitems-group2">
        <li class="fore1">
            <a target="_blank" href="#">全球购</a>
        </li>
        <li class="fore1">
            <a target="_blank" href="#">闪购</a>
        </li>
        <li class="fore1">
            <a target="_blank" href="#">团购</a>
        </li>
        <li class="fore1">
            <a target="_blank" href="#">拍卖</a>
        </li>
        <li class="fore1">
            <a target="_blank" href="#">金融</a>
        </li>
    </ul>
</div>
```

**Comment by Easy-MJ** [comment]
样式结构设计
``` css
#navitems-2014 {
    float: left;
    position: relative;
    z-index: 2;
}

#navitems-2014 li a {
    font-size: 16px;
}

#navitems-2014 a:hover {
    color: #C81623;
}

#navitems-2014 a {
    height: 44px;
    padding: 0 20px;
    text-align: center;
    text-decoration: none;
    font: 400 15px/44px "microsoft yahei";
    color: #333;
}

#navitems-2014 .spacer, #navitems-2014 a, #navitems-2014 li, #navitems-2014 ul {
    float: left;
}
```
