### ISSUE TITLE
任务13 首页滚动广告部分的设计

### ISSUE THREAD

**Issue by Easy-MJ** [Easy-MJ/html-study#13]

**Comment by Easy-MJ** [comment]
循环滚动广告的页面结构设计
``` html
<div id="focus">
    <div class="slider">
        <ul class="slider-main" style="position: relative;">
            <li class="slider-panel">
                <div class="inner">
                    <a target="_blank" href="#">
                        <img width="730" height="454" alt="" src="images/57c8f3d2N1f0a34ba.jpg">
                    </a>
                </div>
            </li>
        </ul>
    </div>
</div>
```

**Comment by Easy-MJ** [comment]
样式结构设计
``` css
#focus {
    margin: 0 auto; /*水平居中对齐*/
    width: 1210px;
    position: relative;
}

#focus .slider {
    height: 466px;
}

#focus .slider-panel {
    width: 100%;
    height: 466px;
    position: absolute;
    z-index: 1;
    opacity: 1;
}

#focus .slider-panel .inner {
    width: 1210px;
    margin: 0 auto;
    height: 466px;
    overflow: hidden;
}

#focus .slider-panel a {
    display: block;
    overflow: hidden;
    zoom: 1;
    width: 730px;
    margin: 12px 250px 0 220px;
    height: 454px;
}
```

**Comment by Easy-MJ** [comment]
底部滚动按钮页面结构
```html
<!--滚动按钮部分-->
<div class="slider-extra">
    <ul class="slider-nav">
        <li class="slider-item">1</li>
        <li class="slider-item slider-selected">2</li>
        <li class="slider-item">3</li>
        <li class="slider-item">4</li>
        <li class="slider-item">5</li>
        <li class="slider-item">6</li>
    </ul>
    <div class="slider-page" style="display: block;">
        <a href="javascript:void(0)" class="slider-prev">&lt;</a>
        <a href="javascript:void(0)" class="slider-next">&gt;</a>
    </div>
</div>
```

**Comment by Easy-MJ** [comment]
底部滚动按钮样式结构
``` css
#focus .slider-prev { /*左右两侧箭头样式*/
    left: 220px;
}

#focus .slider-nav, #focus .slider-next, #focus .slider-prev {
    position: absolute;
    z-index: 4;
}

.slider-page a {
    position: absolute;
    top: 50%;
    margin-top: -31px;
    z-index: 1;
    display: block;
    width: 28px;
    height: 62px;
    line-height: 62px;
    background: gray;
    background: rgba(0,0,0,.2);
    filter: progid:DXImageTransform.Microsoft.gradient(startColorstr=#32000000, endColorstr=#32000000);
    color: #fff;
    text-align: center;
    font-size: 22px;
    font-weight: 400;
    font-family: simsun;
}

#focus .slider-next {
    right: 260px;
}
```
