### ISSUE TITLE
任务14 滚动广告右边的内容的实现

### ISSUE THREAD

**Issue by Easy-MJ** [Easy-MJ/html-study#14]

**Comment by Easy-MJ** [comment]
页面结构设计
``` html
<div id="focus-extra" class="w">
        <!--快报-->
        <div id="news" class="m">
            <div class="mt">
                <h2>京东快报</h2>
                <div class="extra"><a target="_blank" href="#">更多 &gt;</a></div>
            </div>
            <div class="mc">
                <ul>
                    <li><a target="_blank" href="#"><span>[特惠]</span>买海岛游，送婚纱照！</a></li>
                    <li><a target="_blank" href="#"><span>[公告]</span> “放心肉” 就在京东生鲜</a></li>
                    <li><a target="_blank" href="#"><span>[特惠]</span>京东超市跨品类满199减100</a></li>
                    <li><a target="_blank" href="#"><span>[公告]</span>贵州扶贫馆 高原香茗邀你赏</a></li>
                    <li><a target="_blank" href="#"><span>[特惠]</span>中秋送洋酒8折再叠优惠券！</a></li>
                </ul>
            </div>
        </div>
        <!--生活服务-->
        <div id="lifeserv" class="m">
            <div class="mt">
                <h2>生活服务</h2>
                <div class="extra"></div>
            </div>
            <div class="mc">
                <ul>
                    <li class="fore1">
				        <a class="cw-icon" target="_blank" href="#" style="padding-top: 41px;">
					        <i class="ci-left" style="top: 13px;background-image: url(images/57620a6fN77b2b8af.png);"></i>
                            <span>话费</span>
                            <i class="ci-tip" style="width:12px;height:15px;top:0px;right:0px;background: url(images/55fa8359Ncfd7029c.png);_background: url(images/55fa8359Ncfd7029c.png) no-repeat 0 0"></i>
				        </a>
			        </li>
                    <li class="fore2">
				        <a class="cw-icon" target="_blank" href="#" style="padding-top: 41px;">
					        <i class="ci-left" style="top: 13px;background-image: url(images/57620a6fN77b2b8af.png);"></i>
                            <span>机票</span>
				        </a>
			        </li>
                    <li class="fore1">
				        <a class="cw-icon" target="_blank" href="#" style="padding-top: 41px;">
					        <i class="ci-left" style="top: 13px;background-image: url(images/57620a6fN77b2b8af.png);"></i>
                            <span>电影票</span>
				        </a>
			        </li>
                    <li class="fore1">
				        <a class="cw-icon" target="_blank" href="#" style="padding-top: 41px;">
					        <i class="ci-left" style="top: 13px;background-image: url(images/57620a6fN77b2b8af.png);"></i>
                            <span>游戏</span>
				        </a>
			        </li>
                    <li class="fore1">
				        <a class="cw-icon" target="_blank" href="#" style="padding-top: 41px;">
					        <i class="ci-left" style="top: 13px;background-image: url(images/57620a6fN77b2b8af.png);"></i>
                            <span>话费</span>
				        </a>
			        </li>
                    <li class="fore2">
				        <a class="cw-icon" target="_blank" href="#" style="padding-top: 41px;">
					        <i class="ci-left" style="top: 13px;background-image: url(images/57620a6fN77b2b8af.png);"></i>
                            <span>机票</span>
				        </a>
			        </li>
                    <li class="fore1">
				        <a class="cw-icon" target="_blank" href="#" style="padding-top: 41px;">
					        <i class="ci-left" style="top: 13px;background-image: url(images/57620a6fN77b2b8af.png);"></i>
                            <span>电影票</span>
				        </a>
			        </li>
                    <li class="fore1">
				        <a class="cw-icon" target="_blank" href="#" style="padding-top: 41px;">
					        <i class="ci-left" style="top: 13px;background-image: url(images/57620a6fN77b2b8af.png);"></i>
                            <span>游戏</span>
				        </a>
			        </li>
                    <li class="fore1">
				        <a class="cw-icon" target="_blank" href="#" style="padding-top: 41px;">
					        <i class="ci-left" style="top: 13px;background-image: url(images/57620a6fN77b2b8af.png);"></i>
                            <span>话费</span>
				        </a>
			        </li>
                    <li class="fore2">
				        <a class="cw-icon" target="_blank" href="#" style="padding-top: 41px;">
					        <i class="ci-left" style="top: 13px;background-image: url(images/57620a6fN77b2b8af.png);"></i>
                            <span>机票</span>
				        </a>
			        </li>
                    <li class="fore1">
				        <a class="cw-icon" target="_blank" href="#" style="padding-top: 41px;">
					        <i class="ci-left" style="top: 13px;background-image: url(images/57620a6fN77b2b8af.png);"></i>
                            <span>电影票</span>
				        </a>
			        </li>
                    <li class="fore1">
				        <a class="cw-icon" target="_blank" href="#" style="padding-top: 41px;">
					        <i class="ci-left" style="top: 13px;background-image: url(images/57620a6fN77b2b8af.png);"></i>
                            <span>游戏</span>
				        </a>
			        </li>
                </ul>
            </div>
        </div>
        <!--广告区-->
        <div id="right-pic" class="m">
            <div class="mc">
                <a href="#" target="_blank">
                    <img src="images/57d20e41N36605683.png" alt="" width="250" height="75">
                </a>
            </div>
        </div>
    </div>
```

**Comment by Easy-MJ** [comment]
样式代码设计
``` css
/**快报样式*/
#focus-extra {
    position: relative;
    z-index: 8;
    top: -466px;
}

.w #news {
    height: 163px;
}

#news {
    height: 200px;
    width: 248px;
    overflow: hidden;
    top: 12px;
    border: solid 1px #e4e4e4;
    border-bottom: 0;
}

#lifeserv, #news {
    position: absolute;
    right: 0;
    padding: 0;
    background: rgba(255,255,255,.85);
    filter: progid:DXImageTransform.Microsoft.gradient(startColorstr=#BBFFFFFF, endColorstr=#BBFFFFFF);
}

.m, .mb, .mc, .mt, .p-detail, .p-img, .p-market, .p-name, .p-price, .sm, .smb, .smc, .smt {
    overflow: hidden;
}

.w #news .mt {
    height: 32px;
    line-height: 32px;
}

#lifeserv .mt, #news .mt {
    padding: 0 15px;
    border-bottom: 1px dotted #E8E8E7;
    height: 43px;
    line-height: 43px;
}

.w #news .mc {
    height: 120px;
    padding-top: 5px;
}

#news .mc {
    height: 140px;
    padding: 8px 0 0 15px;
}

#focus-extra h2 {
    float: left;
}

#lifeserv h2, #news h2 {
    font-size: 16px;
}

h2, h3 {
    font-family: "microsoft yahei";
    font-weight: 400;
}

#news .mc li {
    line-height: 24px;
    height: 24px;
}

#news li {
    width: 210px;
    height: 27px;
    line-height: 27px;
    overflow: hidden;
}

#news li span {
    font-weight: 700;
    margin-right: 5px;
}

#focus-extra .mt .extra {
    float: right;
    font-family: consolas;
}

/**生活服务样式*/
.w #lifeserv {
    top: 176px;
    border-top: solid 1px #e4e4e4;
}

#lifeserv {
    top: 213px;
    border: solid 1px #e4e4e4;
    border-top: dashed 1px #e4e4e4;
    overflow: hidden;
    width: 248px;
}

.w #lifeserv .mt {
    display: none;
}

#lifeserv .mc {
    height: 208px;
    position: relative;
}

#lifeserv ul {
    position: relative;
    width: 260px;
    height: 209px;
    overflow: hidden;
}

#lifeserv li {
    _position: relative;
    float: left;
    display: inline;
    width: 62px;
    height: 70px;
    border-right: 1px solid #E8E8E7;
    border-bottom: 1px solid #E8E8E7;
    overflow: hidden;
    cursor: pointer;
}

#lifeserv li a {
    display: block;
    width: 62px;
    height: 28px;
    padding-top: 41px;
    line-height: 28px;
    text-align: center;
    text-decoration: none;
    cursor: pointer;
}

#lifeserv .fore1 .ci-left {
    background: url(images/icon_lifeserv.png) no-repeat 0 0;
}

#lifeserv .fore2 .ci-left {
    background: url(//misc.360buyimg.com/product/home/1.0.0/widget/lifeserv/i/icon_lifeserv.png) no-repeat 0 -25px;
}

#lifeserv .ci-left {
    top: 13px;
    left: 18px;
    width: 25px;
    height: 25px;
}

/**广告位样式*/
#right-pic {
    position: absolute;
    right: 0;
    padding: 0;
    background: rgba(255,255,255,.85);
    overflow: hidden;
    width: 250px;
    height: 75px;
    top: 391px;
    filter: progid:DXImageTransform.Microsoft.gradient(startColorstr=#BBFFFFFF, endColorstr=#BBFFFFFF);
}
```
