### ISSUE TITLE
任务2 顶部菜单的左边内容的制作

### ISSUE THREAD

**Issue by Easy-MJ** [Easy-MJ/html-study#2]

**Comment by Easy-MJ** [comment]
页面结构：
``` html
<ul class="fl">
    <li id="ttbar-mycity" class="dorpdown">
        <div class="dt cw-icon ui-areamini-text-wrap">
            <i class="ci-right">
                <s>◇</s>
            </i>
            送至：<span>北京</span>
        </div>
    </li>
</ul>
```
样式结构
``` css
/**快捷菜单左侧列表样式*/
#shortcut-2014 #ttbar-mycity {
    padding-left: 0;
}

#shortcut-2014 li.dorpdown {
    z-index: 13;
}

#shortcut-2014 li {
    float: left;
    height: 30px;
    padding: 0 2px;
}

.dorpdown {
    position: relative;
}

#shortcut-2014 #ttbar-mycity .dt {
    padding: 0 25px 0 10px;
}

#shortcut-2014 .dt {
    float: left;
    padding: 0 8px;
}

.cw-icon {
    position: relative;
    cursor: default;
    zoom: 1;
}

#shortcut-2014 li:hover .ci-right { /**通过旋转180度控制箭头方向向上*/
    transform: rotate(180deg);
    -webkit-transform: rotate(180deg);
}

#shortcut-2014 .ci-right {
    top: 12px;
    right: 8px;
    height: 7px;
    overflow: hidden;
    font: 400 15px/15px consolas;
    color: #6A6A6A;
    transition: transform .1s ease-in 0s;
    -webkit-transition: -webkit-transform .1s ease-in 0s;
}

.cw-icon .i, .cw-icon i {
    display: block;
    position: absolute;
    overflow: hidden;
}

#shortcut-2014 .ci-right s { /**控制箭头向下*/
    position: relative;
    top: -7px;
    text-decoration: none;
}
```
