### ISSUE TITLE
任务3 顶部菜单箭头翻转效果的实现

### ISSUE THREAD

**Issue by Easy-MJ** [Easy-MJ/html-study#3]

**Comment by Easy-MJ** [comment]
- 原理：通过旋转控制箭头方向调整
样式代码
``` css
#shortcut-2014 li:hover .ci-right { /**通过旋转180度控制箭头方向向上*/
    transform: rotate(180deg);
    -webkit-transform: rotate(180deg);
}
```
