### ISSUE TITLE
任务4 顶部菜单右边的内容的布局

### ISSUE THREAD

**Issue by Easy-MJ** [Easy-MJ/html-study#4]

**Comment by Easy-MJ** [comment]
页面代码
``` html
<ul class="fr">
    <li id="ttbar-login">
        <a href="javascript:login();" class="link-login">你好，请登录</a>&nbsp;&nbsp;
        <a href="javascript:regist();" class="link-regist style-red">免费注册</a>
    </li>
    <li class="spacer"></li>
    <li>
        <div class="dt">
            <a target="_blank" href="#">我的订单</a>
        </div>
    </li>
    <li class="spacer"></li>
    <li id="ttbar-myjd" class="dorpdown">
        <div class="dt cw-icon">
            <i class="ci-right"><s>◇</s></i>
            <a target="_blank" href="#">我的京东</a>
        </div>
    </li>
    <li class="spacer"></li>
    <li>
        <div class="dt">
            <a target="_blank" href="#">京东会员</a>
        </div>
    </li>
    <li class="spacer"></li>
    <li>
        <div class="dt">
            <a target="_blank" href="#">企业采购</a>
        </div>
    </li>
    <li class="spacer"></li>
    <li class="dorpdown" id="ttbar-apps">
        <div class="dt cw-icon">
            <i class="ci-left"></i>
            <i class="ci-right"><s>◇</s></i>
            <a target="_blank" href="#">手机京东</a>
        </div>
    </li>
    <li class="spacer"></li>
    <li class="dorpdown" id="ttbar-atte">
        <div class="dt cw-icon">
            <i class="ci-right"><s>◇</s></i>关注京东
        </div>
    </li>
    <li class="spacer"></li>
    <li class="dorpdown" id="ttbar-serv">
        <div class="dt cw-icon">
            <i class="ci-right"><s>◇</s></i>客户服务
        </div>
    </li>
    <li class="spacer"></li>
    <li class="dorpdown" id="ttbar-navs">
        <div class="dt cw-icon">
            <i class="ci-right"><s>◇</s></i>网站导航
        </div>
    </li>
</ul>
```
样式代码
``` css
/**快捷菜单右侧列表样式*/
#shortcut-2014 #ttbar-login {
    margin-right: 10px;
}

#shortcut-2014 #ttbar-login .link-login {
    font-family: "verdana,simsun";
}

#shortcut-2014 .style-red {
    color: #C81623;
}

#shortcut-2014 li {
    float: left;
    height: 30px;
    padding: 0 2px;
}

#shortcut-2014 li.spacer { /**分隔线样式*/
    width: 1px;
    height: 12px;
    margin-top: 9px;
    padding: 0;
    background: #ddd;
    overflow: hidden;
}

#shortcut-2014 .dt {
    float: left;
    padding: 0 8px;
}

#ttbar-myjd .dt {
    width: 49px;
    padding-right: 25px;
}

#shortcut-2014 #ttbar-apps .dt {
    padding-left: 25px;
    padding-right: 25px;
}

#shortcut-2014 #ttbar-apps .dt .ci-left {
    top: 5px;
    left: 7px;
    width: 15px;
    height: 20px;
    background: url(//misc.360buyimg.com/jdf/1.0.0/unit/globalImages/1.0.0/jd2015img.png) 0 0 no-repeat;
}

#shortcut-2014 #ttbar-atte .dt, #shortcut-2014 #ttbar-serv .dt, #shortcut-2014 #ttbar-navs .dt {
    width: 49px;
    padding-right: 25px;
}

#shortcut-2014 li#ttbar-navs {
    padding: 0 1px 0 2px;
}
```

**Comment by Easy-MJ** [comment]
- 分隔线实现原理：li标签设置背景色、宽度及高度

页面代码
``` html
<li class="spacer"></li>
```

样式代码
``` css
#shortcut-2014 li.spacer { /**分隔线样式*/
    width: 1px;
    height: 12px;
    margin-top: 9px;
    padding: 0;
    background: #ddd;
    overflow: hidden;
}
```

**Comment by Easy-MJ** [comment]
- 菜单左侧图标实现原理：

页面结构
``` html
<li class="dorpdown" id="ttbar-apps">
    <div class="dt cw-icon">
        <i class="ci-left"></i>
        <i class="ci-right"><s>◇</s></i>
        <a target="_blank" href="#">手机京东</a>
    </div>
</li>
```

样式结构
``` css
外层容器设置padding-left和padding-right值用来存放左右侧的图标
#shortcut-2014 #ttbar-apps .dt {
    padding-left: 25px;
    padding-right: 25px;
}

外层容器设置为相对定位
.cw-icon {
    position: relative;
    cursor: default;
    zoom: 1;
}

图标的标签设置为块元素，并设置为绝对定位
.cw-icon .i, .cw-icon i {
    display: block;
    position: absolute;
    overflow: hidden;
}

图标标签设置宽度、高度、背景图片及绝对定位位置
#shortcut-2014 #ttbar-apps .dt .ci-left {
    top: 5px;
    left: 7px;
    width: 15px;
    height: 20px;
    background: url(//misc.360buyimg.com/jdf/1.0.0/unit/globalImages/1.0.0/jd2015img.png) 0 0 no-repeat;
}

右侧图标原理相同
#shortcut-2014 .ci-right {
    top: 12px;
    right: 8px;
    height: 7px;
    overflow: hidden;
    font: 400 15px/15px consolas;
    color: #6A6A6A;
    transition: transform .1s ease-in 0s;
    -webkit-transition: -webkit-transform .1s ease-in 0s;
}

#shortcut-2014 .ci-right s { /**控制箭头向下*/
    position: relative;
    top: -7px;
    text-decoration: none;
}
```
