### ISSUE TITLE
任务5 元素被挤压现象的解决办法

### ISSUE THREAD

**Issue by Easy-MJ** [Easy-MJ/html-study#5]

**Comment by Easy-MJ** [comment]
如果给标签添加鼠标悬浮上面增加细边框的样式，则会出现因为宽度增加导致元素抖动的问题，解决该问题的思路有两个：1. 绝对定位； 2. 减小父容器的宽度（抵消增加的宽度）；

``` css
#shortcut-2014 .dorpdown:hover .dt{ /**鼠标放置到标签上出现细边框左右各1px*/
    background:#fff;
    border-left: 1px solid #ddd;
    border-right: 1px solid #ddd;
}

#shortcut-2014 .dorpdown:hover{ /**抵消两边增加的2px*/
    padding: 0 1px;
}
```
