### ISSUE TITLE
任务6 京东首页logo的设计

### ISSUE THREAD

**Issue by Easy-MJ** [Easy-MJ/html-study#6]

**Comment by Easy-MJ** [comment]
基本框架结构：一个大层，包含四个子层
``` html
<div class="w">
    <div id="logo-2014"></div>
    <div id="search-2014"></div>
    <div id="settleup-2014" class="dorpdown"></div>
    <div id="hotwords-2014"></div>
</div>
```

**Comment by Easy-MJ** [comment]
左侧logo部分
html页面结构
``` html
<div id="logo-2014">
    <a href="#" class="logo">京东</a>
</div>
```
css样式结构
``` css
#logo-2014 {    /**logo部分样式*/
    position: relative;
    z-index: 12; /**下拉的时候能够覆盖logo层*/
    float: left;
    width: 362px;/**如果是浮动元素，宽度默认是自动计算的，如果想要固定宽度必须手动指定宽度*/
    height: 60px;
    padding: 20px 0;/**内容居中可以使用上下填充相同的高度实现*/
}

#logo-2014 .logo {
    display: block;
    width: 270px;
    height: 60px;
    background: url(images/logo-201305.png) no-repeat 0 0;
    text-indent: -20000px;
}
```
