### ISSUE TITLE
任务7 京东搜索框和搜索按钮的制作

### ISSUE THREAD

**Issue by Easy-MJ** [Easy-MJ/html-study#7]

**Comment by Easy-MJ** [comment]
搜索框部分
页面结构：
``` html
<div id="search-2014">
    <div class="form">
        <input class="text" style="color: rgb(153, 153, 153);" value="移动电源">
        <button class="button cw-icon">搜索</button>
    </div>
</div>
```
样式结构：
``` css
#search-2014 {  /**搜索框部分样式*/
    position: relative;
    z-index: 11;
    float: left;
    width: auto;
    margin-top: 25px;
}

#search-2014 .form {
    width: auto;
    height: 36px;
}

#search-2014 .text {
    float: left;
    width: 446px;
    height: 24px;
    line-height: 24px;/*行高与高度相等，文字垂直居中对齐*/
    color: #666;
    padding: 4px;
    margin-bottom: 4px;
    border-width: 2px 0 2px 2px;
    border-color: #B61D1D;
    border-style: solid;
    outline: 0;
    font-size: 14px;
    font-family: "microsoft yahei";
}

#search-2014 .button {
    float: left;
    width: 82px;
    height: 36px;
    background: #B61D1D;
    border: none;/*去除边框*/
    line-height: 1;/*垂直居中对齐矫正*/
    color: #fff;
    font-family: "Microsoft YaHei";
    font-size: 16px;
    cursor: pointer;/*手型样式*/
}
```
