### ISSUE TITLE
任务8 我的购物的制作

### ISSUE THREAD

**Issue by Easy-MJ** [Easy-MJ/html-study#8]

**Comment by Easy-MJ** [comment]
我的购物车，图标原理：
- 外层div容器相对定位，并且通过padding-left和padding-right预留好图标显示的位置，然后里面通过几个i标签的绝对定位实现

页面结构
``` html
<div id="settleup-2014" class="dorpdown">
    <div class="cw-icon">
        <i class="ci-left"></i>
        <i class="ci-right">&gt;</i>
        <i class="ci-count" id="shopping-amount">0</i>
        <a target="_blank" href="#">我的购物车</a>
    </div>
</div>
```
样式结构
``` css
#settleup-2014 { /**我的购物车部分样式*/
    float: right; /*右浮动*/
    z-index: 11;
    height: 36px;
    margin-top: 25px;
    margin-right: 65px;
}

#settleup-2014 .cw-icon {
    width: 75px;
    height: 34px;
    border: 1px solid #DFDFDF;
    padding: 0 28px 0 36px;/*左右边距空隙用来存放图标*/
    background: #F9F9F9;
    text-align: center;
    line-height: 34px;
}

#settleup-2014 .ci-left {
    top: 9px;
    left: 18px;
    width: 18px;
    height: 16px;
    background: url(images/00.png) 0 -58px no-repeat;
    _background: url(images/00.png) 0 -91px no-repeat;/*兼容IE的早期版本bug问题*/
}

#settleup-2014 .ci-right {
    top: 11px; /*使用top、left等必须有position并且不能为static修饰的*/
    right: 10px;
    width: 7px;
    height: 13px;
    overflow: hidden;
    font: 400 13px/13px simsun;
    color: #999;
}

#settleup-2014 .ci-count {
    position: absolute;
    top: -4px;
    left: 104px;
    display: inline-block;
    padding: 1px 2px;
    font-size: 12px;
    line-height: 12px;
    color: #fff;
    background-color: #c81623;
    border-radius: 7px 7px 7px 0;/*气泡样式*/
    min-width: 12px;
    text-align: center;
}
```
