### ISSUE TITLE
任务9 热门搜索部分的设计

### ISSUE THREAD

**Issue by Easy-MJ** [Easy-MJ/html-study#9]

**Comment by Easy-MJ** [comment]
热门搜索关键词

页面结构
``` html
<div id="hotwords-2014">
    <a href="#" target="_blank" class="style-red">疯减1200</a>
    <a href="#" target="_blank">Beats 预约</a>
    <a href="#" target="_blank">工具9.9</a>
    <a href="#" target="_blank">手表抽奖</a>
    <a href="#" target="_blank">开学必备</a>
    <a href="#" target="_blank">实木餐桌</a>
    <a href="#" target="_blank">毛毯</a>
    <a href="#" target="_blank">1元专享</a>
    <a href="#" target="_blank">护膝</a>
</div>
```
样式结构
``` css
#hotwords-2014 { /**热门搜索关键词部分样式*/
    float: left; /*左浮动*/
    width: 518px;
    height: 20px;
    line-height: 20px;
    overflow: hidden; /*超出部分隐藏*/
}

#hotwords-2014 a {
    float: left;
    white-space: nowrap;/*不要换行*/
    margin-right: 10px;
}

.style-red {
    color: #C81623;
}
```
